<e>  ::=  <e>+<e>|
          <e>-<e>|
          <e>*<e>|
          <e>+<e>|
          <e>-<e>|
          <e>*<e>|
          <c><c>.<c><c>|
          <c><c>.<c><c>|
          <c><c>.<c><c>|
          <c><c>.<c><c>|
          my_payoff | opponent_payoff | my_payoff | opponent_payoff

<c>  ::= 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9